spring:
  profiles: locale
  datasource:
    url: jdbc:postgresql://localhost:5432/applicationForms
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    schema: public